/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VendorRegisterRouteImport } from './routes/vendor-register'
import { Route as VendorLoginRouteImport } from './routes/vendor-login'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressRouteImport } from './routes/address'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor-register',
  path: '/vendor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor-login',
  path: '/vendor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VendorProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/vendor-login': typeof VendorLoginRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$id': typeof ShopIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/vendor-login': typeof VendorLoginRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$id': typeof ShopIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/vendor-login': typeof VendorLoginRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$id': typeof ShopIdRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/address'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/profile'
    | '/register'
    | '/shop'
    | '/vendor'
    | '/vendor-login'
    | '/vendor-register'
    | '/wishlist'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/vendors'
    | '/shop/$id'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin/'
    | '/shop/'
    | '/vendor/'
    | '/vendor/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/address'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/profile'
    | '/register'
    | '/vendor-login'
    | '/vendor-register'
    | '/wishlist'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/vendors'
    | '/shop/$id'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin'
    | '/shop'
    | '/vendor'
    | '/vendor/products/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/address'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/payment'
    | '/profile'
    | '/register'
    | '/shop'
    | '/vendor'
    | '/vendor-login'
    | '/vendor-register'
    | '/wishlist'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/vendors'
    | '/shop/$id'
    | '/vendor/analytics'
    | '/vendor/orders'
    | '/vendor/products'
    | '/admin/'
    | '/shop/'
    | '/vendor/'
    | '/vendor/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddressRoute: typeof AddressRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  VendorLoginRoute: typeof VendorLoginRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-register': {
      id: '/vendor-register'
      path: '/vendor-register'
      fullPath: '/vendor-register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-login': {
      id: '/vendor-login'
      path: '/vendor-login'
      fullPath: '/vendor-login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorProductsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopIdRoute: typeof ShopIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIdRoute: ShopIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface VendorProductsRouteChildren {
  VendorProductsNewRoute: typeof VendorProductsNewRoute
}

const VendorProductsRouteChildren: VendorProductsRouteChildren = {
  VendorProductsNewRoute: VendorProductsNewRoute,
}

const VendorProductsRouteWithChildren = VendorProductsRoute._addFileChildren(
  VendorProductsRouteChildren,
)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRouteWithChildren
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRouteWithChildren,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddressRoute: AddressRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  VendorLoginRoute: VendorLoginRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
